name: CI on dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Test (xcodeproj)
      run: xcodebuild clean build -project OverTheRainbow/OverTheRainbow.xcodeproj -scheme OverTheRainbow -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2'
    
