name: CI on dev

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: CocoaPod Install
      run: |
        cd ./OverTheRainbow
        pod install
    - name: Build & Test (xcodeproj)
      run: |
        xcodebuild clean build \
        -workspace OverTheRainbow/OverTheRainbow.xcworkspace \
        -scheme OverTheRainbow -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2'
    
